lib/slack_proxy_web/router.ex
defmodule SlackProxyWeb.Router do
  use SlackProxyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SlackProxyWeb.Auth   # puts current_user in assigns. access control is handled by controllers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SlackProxyWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create, :edit, :update]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/build_proxies", BuildProxyController
  end

  scope "/", SlackProxyWeb do
    pipe_through :api

    post "/build_proxies/:id/buildcomplete", BuildProxyController, :build_complete
    post "/build_proxies/:id/deploycomplete", BuildProxyController, :deploy_complete
  end
end

lib/slack_proxy_web/views/layout_view.ex
defmodule SlackProxyWeb.LayoutView do
  use SlackProxyWeb, :view
end

lib/slack_proxy_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no"/>
    <title>Slack Proxy</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container center">
        <nav role="navigation">
          <ul class="list-group nav-list">
            <%= if @current_user do %>
              <li class="list-group-item nav-item"><%= link "#{@current_user.username} (you)", to: Routes.user_path(@conn, :show, @current_user) %></li>
              <li class="list-group-item nav-item"><%= link "Users", to: Routes.user_path(@conn, :index) %></li>
              <li class="list-group-item nav-item"><%= link "Build Proxies", to: Routes.build_proxy_path(@conn, :index) %></li>
              <li class="list-group-item nav-item">
                <%= link "Log out",
                      to: Routes.session_path(@conn, :delete, @current_user),
                      method: "delete" %>
              </li>
            <% else %>
              <li class="list-group-item nav-item"><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="/" class="phx-logo">
          <img class="bender" src="<%= Routes.static_path(@conn, "/images/bender.png") %>"
              alt="Slack Proxy Friendly Robot"/>
        </a>
      </section>
    </header>

    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>